In [1]:
import numpy as np
import pandas as pd

In [2]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies=movies.merge(credits,on='title')

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [7]:
# genres
# id
# keywords 
# title
# overview
# cast
# crew

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [9]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [11]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [12]:
movies.dropna(inplace=True)

In [13]:
movies.duplicated().sum()

0

In [14]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
import ast
def convert(obj):
    L= []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [16]:
movies['genres']=movies['genres'].apply(convert)

In [17]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
movies['keywords']= movies['keywords'].apply(convert)

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [21]:
import ast
def conv(obj):
    L= []
    counter=0
    for i in ast.literal_eval(obj):
        if counter !=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [22]:
movies['cast']=movies['cast'].apply(conv)

In [23]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [24]:
import ast
def director(obj):
    L= []
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [25]:
movies['crew']=movies['crew'].apply(director)

In [26]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [27]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [28]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [29]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i  in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i  in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i  in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i  in x])

In [30]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [31]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [33]:
new_df = movies[['movie_id','title','tags']]

In [34]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [35]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\win\AppData\Local\Temp\ipykernel_10332\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [36]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [37]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\win\AppData\Local\Temp\ipykernel_10332\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [38]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [39]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in c:\programdata\anaconda3\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\programdata\anaconda3\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\programdata\anaconda3\lib\site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\programdata\anaconda3\lib\site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from nltk) (4.65.0)
Requirement already satisfied: colorama in c:\users\win\appdata\roaming\python\python311\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [40]:
import nltk

In [41]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [42]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [43]:
new_df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bondâ€™ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [45]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [46]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [47]:
from sklearn.metrics.pairwise import cosine_similarity

In [48]:
similarity=cosine_similarity(vectors)

In [49]:
sorted(similarity[0],reverse=True)

[1.0,
 0.26089696604360174,
 0.2581988897471611,
 0.25302403842552984,
 0.25110592822973776,
 0.24944382578492943,
 0.24397501823713333,
 0.243599382882345,
 0.23904572186687872,
 0.2344036154692477,
 0.22677868380553634,
 0.2238868314198225,
 0.22230800575069137,
 0.22190115272469205,
 0.22131333406899523,
 0.2193633988428327,
 0.2173253797873328,
 0.21653278478430668,
 0.2164218276749025,
 0.2162249910469341,
 0.2162249910469341,
 0.21602468994692864,
 0.21602468994692864,
 0.21251185925162067,
 0.2114722130550724,
 0.21147221305507238,
 0.21096325392232296,
 0.2059714602177749,
 0.20291986247835692,
 0.20283702113484398,
 0.19920476822239894,
 0.19889806323953876,
 0.1980534816610477,
 0.19518001458970666,
 0.19518001458970666,
 0.19451950503185494,
 0.1938916835823703,
 0.19320245583349133,
 0.19317811536651805,
 0.19166296949998196,
 0.1901597073139162,
 0.1893524273324603,
 0.1889822365046136,
 0.18832944617230335,
 0.18832944617230335,
 0.18708286933869706,
 0.18478728707195913,
 0.18478728707195913,
 0.1831403087002079,
 0.1825741858350554,
 0.18257418583505536,
 0.18018749253911176,
 0.17928429140015903,
 0.1765469659009499,
 0.1763834207376394,
 0.17622684421256032,
 0.17445567519772937,
 0.17251638983558856,
 0.17251638983558856,
 0.1717355162964367,
 0.17142857142857143,
 0.17142857142857143,
 0.17036708399998393,
 0.1690308509457033,
 0.1690308509457033,
 0.1690308509457033,
 0.1690308509457033,
 0.16903085094570328,
 0.16574838603294897,
 0.16574838603294897,
 0.16408253082847338,
 0.16265001215808886,
 0.16265001215808886,
 0.16239958858823,
 0.16239958858823,
 0.16035674514745463,
 0.16035674514745463,
 0.15971914124998493,
 0.15694120514358612,
 0.15694120514358612,
 0.1564921592871903,
 0.1553638665664663,
 0.15430334996209188,
 0.15289415743128765,
 0.15289415743128765,
 0.15289415743128765,
 0.15179418517972906,
 0.15179418517972906,
 0.15179418517972906,
 0.15118578920369088,
 0.15118578920369088,
 0.15026857675938213,
 0.14953343588376802,
 0.14754222271266348,
 0.14754222271266348,
 0.14754222271266348,
 0.14638501094227999,
 0.1456438162508838,
 0.1449427589131121,
 0.1449427589131121,
 0.1449427589131121,
 0.1449427589131121,
 0.14414999403128942,
 0.14414999403128942,
 0.14414999403128942,
 0.14414999403128942,
 0.14414999403128942,
 0.14285714285714285,
 0.14201432049934523,
 0.14098147537004826,
 0.14085904245475275,
 0.14085904245475275,
 0.1406421692815486,
 0.1406421692815486,
 0.13930903806377162,
 0.1389425035941821,
 0.1389425035941821,
 0.13801311186847084,
 0.13801311186847084,
 0.13801311186847084,
 0.13801311186847084,
 0.13801311186847082,
 0.13710212427677043,
 0.13710212427677043,
 0.13710212427677043,
 0.13662601021279464,
 0.13662601021279464,
 0.13552618543578768,
 0.13533299049019168,
 0.13533299049019168,
 0.13533299049019168,
 0.13522468075656266,
 0.13522468075656266,
 0.13522468075656266,
 0.13522468075656266,
 0.13433209885189348,
 0.1336306209562122,
 0.13259870882635919,
 0.13259870882635919,
 0.13259870882635919,
 0.13259870882635919,
 0.13259870882635919,
 0.13199091933711365,
 0.1309307341415954,
 0.13041013273932528,
 0.13041013273932528,
 0.13041013273932528,
 0.13041013273932528,
 0.1301200097264711,
 0.1301200097264711,
 0.12888481555661674,
 0.12777531299998796,
 0.12777531299998796,
 0.12777531299998796,
 0.12777531299998796,
 0.12741179785940637,
 0.12741179785940637,
 0.12741179785940637,
 0.12598815766974242,
 0.12555296411486888,
 0.12555296411486888,
 0.12555296411486888,
 0.12555296411486888,
 0.12555296411486888,
 0.1246111965698067,
 0.1246111965698067,
 0.12461119656980668,
 0.12344267996967351,
 0.12344267996967351,
 0.12344267996967351,
 0.12327841818038447,
 0.12327841818038447,
 0.12327841818038446,
 0.12298800925361816,
 0.12298800925361816,
 0.12298800925361816,
 0.12298800925361816,
 0.12198750911856666,
 0.12198750911856665,
 0.12143534814378325,
 0.12073632210407378,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343935,
 0.11952286093343935,
 0.11952286093343935,
 0.11952286093343935,
 0.11952286093343935,
 0.1183452670827877,
 0.1183452670827877,
 0.11769797726729994,
 0.11769797726729994,
 0.11769797726729994,
 0.11769797726729994,
 0.11710800875382396,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11609086505314302,
 0.11595420713048966,
 0.11595420713048966,
 0.11595420713048966,
 0.11595420713048966,
 0.11595420713048966,
 0.11501092655705902,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.1129384878631564,
 0.1129384878631564,
 0.1129384878631564,
 0.1129384878631564,
 0.1129384878631564,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.11194341570991125,
 0.11194341570991125,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.1109741904046188,
 0.11097419040461878,
 0.11065666703449763,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10910894511799617,
 0.10826639239215334,
 0.10826639239215334,
 0.10826639239215334,
 0.10826639239215334,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10733469768527294,
 0.10690449676496976,
 0.10690449676496976,
 0.10690449676496976,
 0.10690449676496976,
 0.10690449676496976,
 0.10690449676496976,
 0.10631548679075009,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10460520656316097,
 0.10432810619146021,
 0.10432810619146021,
 0.1043281061914602,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10101525445522107,
 0.10079052613579392,
 0.10079052613579392,
 0.09968895725584535,
 0.09960238411119947,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.09944903161976938,
 0.09862273454430757,
 0.09862273454430757,
 0.09862273454430757,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09658905768325902,
 0.09658905768325902,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09569487529386908,
 0.09561828874675149,
 0.09508728264112047,
 0.09467621366623016,
 0.09467621366623016,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09390602830316849,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09276773134741387,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09200874124564722,
 0.09200874124564722,
 0.09200874124564722,
 0.09200874124564722,
 0.09200874124564722,
 0.09200874124564722,
 0.09116846116771035,
 0.09116846116771035,
 0.09116846116771035,
 0.09116846116771035,
 0.09116846116771035,
 0.09116846116771035,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09009374626955588,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.089554732567929,
 0.089554732567929,
 0.08877935232369503,
 0.08877935232369503,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.0880237696271323,
 0.0880237696271323,
 0.0880237696271323,
 0.0880237696271323,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.086568731069961,
 0.086568731069961,
 0.086568731069961,
 0.08656873106996099,
 0.08656873106996099,
 0.08656873106996099,
 0.08586775814821836,
 0.08586775814821836,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.08518354199999197,
 0.08518354199999197,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08386278693775347,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08322503785764788,
 0.08322503785764788,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.08095109602454656,
 0.08024108542850393,
 0.08021849185198157,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.07859774918918593,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359515,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07655590023509526,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07476671794188403,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07466533929465573,
 0.07396705090823068,
 0.07396705090823068,
 0.07396705090823068,
 0.07396705090823068,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07333587976225689,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07244179326244427,
 0.07244179326244427,
 0.07244179326244427,
 0.07244179326244427,
 0.07244179326244427,
 0.07244179326244427,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07168504827326538,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.0708769911938334,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.0703210846407743,
 0.0703210846407743,
 0.0703210846407743,
 0.0703210846407743,
 0.0703210846407743,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423541,
 0.06900655593423541,
 0.06900655593423541,
 0.06900655593423541,
 0.06837634587578276,
 0.06776309271789384,
 0.06776309271789384,
 0.06776309271789384,
 0.06776309271789384,
 0.06776309271789384,
 0.06776309271789384,
 0.06776309271789384,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06716604942594674,
 0.06716604942594674,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06601782722034923,
 0.06601782722034923,
 0.06601782722034923,
 0.06601782722034923,
 0.0654653670707977,
 0.0654653670707977,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06492654830247076,
 0.06492654830247076,
 0.06492654830247076,
 0.06492654830247076,
 0.06440081861116377,
 0.06440081861116377,
 0.06440081861116377,
 0.06440081861116377,
 0.06417479348158525,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06338656910463875,
 0.06338656910463875,
 0.0628970902033151,
 0.0628970902033151,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06241877839323591,
 0.06241877839323591,
 0.06224220440894771,

In [50]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(539, 0.26089696604360174),
 (1194, 0.2581988897471611),
 (507, 0.25302403842552984),
 (260, 0.25110592822973776),
 (1216, 0.24944382578492943)]

In [51]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [52]:
recommend('Avatar')

Titan A.E.
Small Soldiers
Independence Day
Ender's Game
Aliens vs Predator: Requiem

In [53]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman & Robin
Batman

In [59]:
import pickle

In [60]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [63]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [62]:
pickle.dump(similarity,open('similarity.pkl','wb'))